# Generated by Django 5.2.12 on 2026-03-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('root_hash', models.CharField(max_length=64)),
                ('diploma_count', models.IntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('universite', models.CharField(max_length=200)),
                ('faculte', models.CharField(max_length=200)),
                ('date_obtention', models.DateField()),
                ('mention', models.CharField(choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien'), ('felicitations', 'Félicitations du jury')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='RootHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_hash', models.CharField(max_length=64)),
                ('tree_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerkleLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf_index', models.IntegerField(unique=True)),
                ('leaf_hash', models.CharField(max_length=64)),
                ('diplome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merkle_leaf', to='lots.diplome')),
            ],
        ),
    ]
